package com.dan.myarchitectproject.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dan.myarchitectproject.db.entity.Company;
import com.dan.myarchitectproject.db.entity.Person;

import com.dan.myarchitectproject.db.dao.CompanyDao;
import com.dan.myarchitectproject.db.dao.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyDaoConfig;
    private final DaoConfig personDaoConfig;

    private final CompanyDao companyDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        companyDao = new CompanyDao(companyDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(Company.class, companyDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        companyDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public CompanyDao getCompanyDao() {
        return companyDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
